/**
 * Données fictives en attendant l'implémentation de l'API transactions.
 * Ces données seront remplacées par des appels API réels filtrés par accountId.
 */
export const MOCK_TRANSACTIONS = {
  8349: [
    {
      id: "8349-1",
      date: "June 20th, 2020",
      description: "Golden Sun Bakery",
      amount: 5.0,
      balance: 2082.79,
      type: "Electronic",
      category: "Food",
      notes: "",
    },
    {
      id: "8349-2",
      date: "June 21st, 2020",
      description: "Amazon",
      amount: 45.0,
      balance: 2037.79,
      type: "Electronic",
      category: "Shopping",
      notes: "",
    },
    {
      id: "8349-3",
      date: "June 20th, 2020",
      description: "Golden Sun Bakery",
      amount: 20.0,
      balance: 2097.79,
      type: "Electronic",
      category: "Food",
      notes: "",
    },
    {
      id: "8349-4",
      date: "June 20th, 2020",
      description: "Golden Sun Bakery",
      amount: 30.0,
      balance: 2117.79,
      type: "Electronic",
      category: "Food",
      notes: "",
    },
    {
      id: "8349-5",
      date: "June 20th, 2020",
      description: "Golden Sun Bakery",
      amount: 40.0,
      balance: 2147.79,
      type: "Electronic",
      category: "Food",
      notes: "",
    },
    {
      id: "8349-6",
      date: "June 20th, 2020",
      description: "Golden Sun Bakery",
      amount: 50.0,
      balance: 2187.79,
      type: "Electronic",
      category: "Food",
      notes: "",
    },
  ],
  67124: [
    {
      id: "67124-1",
      date: "June 01st, 2020",
      description: "Interest Payment",
      amount: 12.42,
      balance: 10928.42,
      type: "Deposit",
      category: "Other",
      notes: "Monthly interest",
    },
    {
      id: "67124-2",
      date: "June 08th, 2020",
      description: "Transfer from Checking",
      amount: 500.0,
      balance: 11428.42,
      type: "Transfer",
      category: "Other",
      notes: "",
    },
    {
      id: "67124-3",
      date: "June 12th, 2020",
      description: "Vacation Fund",
      amount: 300.0,
      balance: 11728.42,
      type: "Deposit",
      category: "Other",
      notes: "",
    },
    {
      id: "67124-4",
      date: "June 15th, 2020",
      description: "Bank Fee",
      amount: -5.0,
      balance: 11723.42,
      type: "Fee",
      category: "Other",
      notes: "",
    },
    {
      id: "67124-5",
      date: "June 18th, 2020",
      description: "Transfer to Checking",
      amount: -200.0,
      balance: 11523.42,
      type: "Transfer",
      category: "Other",
      notes: "",
    },
    {
      id: "67124-6",
      date: "June 25th, 2020",
      description: "Interest Adjustment",
      amount: 8.0,
      balance: 11531.42,
      type: "Deposit",
      category: "Other",
      notes: "",
    },
  ],

  5201: [
    {
      id: "5201-1",
      date: "June 02nd, 2020",
      description: "Apple Store",
      amount: -899.0,
      balance: -899.0,
      type: "Card Payment",
      category: "Shopping",
      notes: "iPhone purchase",
    },
    {
      id: "5201-2",
      date: "June 05th, 2020",
      description: "Netflix",
      amount: -15.99,
      balance: -914.99,
      type: "Card Payment",
      category: "Entertainment",
      notes: "",
    },
    {
      id: "5201-3",
      date: "June 08th, 2020",
      description: "Uber",
      amount: -18.5,
      balance: -933.49,
      type: "Card Payment",
      category: "Transport",
      notes: "",
    },
    {
      id: "5201-4",
      date: "June 12th, 2020",
      description: "Pharmacy",
      amount: -32.75,
      balance: -966.24,
      type: "Card Payment",
      category: "Health",
      notes: "",
    },
    {
      id: "5201-5",
      date: "June 18th, 2020",
      description: "Restaurant Bella Vita",
      amount: -68.4,
      balance: -1034.64,
      type: "Card Payment",
      category: "Food",
      notes: "",
    },
    {
      id: "5201-6",
      date: "June 28th, 2020",
      description: "Credit Card Payment",
      amount: 850.0,
      balance: 184.64,
      type: "Payment",
      category: "Other",
      notes: "Partial repayment",
    },
  ],
};

/**
 * Informations statiques des comptes bancaires affichés sur la page Profile.
 * Clé = numéro de compte (correspond au paramètre :accountId dans l'URL).
 * À remplacer par un appel API /user/accounts quand la route sera disponible.
 */
export const ACCOUNTS_INFO = {
  8349: {
    name: "Argent Bank Checking (x8349)",
    balance: "$2,082.79",
    description: "Available Balance",
  },
  67124: {
    name: "Argent Bank Savings (x67124)",
    balance: "$10,928.42",
    description: "Available Balance",
  },
  5201: {
    name: "Argent Bank Credit Card (x5201)",
    balance: "$184.30",
    description: "Current Balance",
  },
};

/** Catégories disponibles pour classifier une transaction */
export const CATEGORIES = [
  "Food",
  "Shopping",
  "Transport",
  "Health",
  "Entertainment",
  "Other",
];
